### ISSUE TITLE
Error message indicates wrong environment variable

### ISSUE THREAD

**Issue by cessationoftime** [cheleb/sbt-dart-plugin#2]
The error message indicates the DART_HOME environment variable should be defined.  When it should actually indicate the DART_SDK environment variable needs to be defined

https://github.com/cheleb/sbt-dart-plugin/blob/master/src/main/scala/sbt/DartProcessor.scala#L17

``` scala
    val DART_SDK = System.getenv("DART_SDK")
    if (DART_SDK == null) {
      sys.error("DART_HOME env variable must be defined!")
```

**Comment by cheleb** [comment]
Fixed in the master, thx for reporting.
