### ISSUE TITLE
sbt-dart-plugin and play 2.3?

### ISSUE THREAD

**Issue by pjean** [cheleb/sbt-dart-plugin#6]
Hi, 

Do you plan to update the plugin in order to be compatible with play 2.3 which uses Auto plugin? 

Thanks

**Comment by cheleb** [comment]
Hi, I've made some attempts at https://github.com/cheleb/sbt-dart ...
This plugin is far more simple than the previous, it just call "pub build"
during the dist/run task.

On Sun, Oct 12, 2014 at 8:54 AM, pjean notifications@github.com wrote:

> Hi,
> 
> Do you plan to update the plugin in order to be compatible with play 2.3
> which uses Auto plugin?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cheleb/sbt-dart-plugin/issues/6.

## 

"Computers are useless. They can only give you answers."
- Pablo Picasso -

**Comment by pjean** [comment]
Ok, I will try it.
Thanks for your work.
